In [1]:
from sklearn.naive_bayes import GaussianNB #高斯貝式分類器
from sklearn.naive_bayes import MultinomialNB #多像式貝式分類器
from sklearn.naive_bayes import BernoulliNB #伯努力貝氏分類器
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
iris=datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X=iris.data
y=iris.target

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

# Gaussian Naive Bayes
主要用於連續變數，比方說特徵長度為幾公分、重量為幾公斤等等。
$$ P(X_j|Y_i)=\frac{1}{\sqrt{2\pi\sigma_{Y_i}^2}} exp(-\frac{(X_j-\mu_{Y_i})^2}{2\sigma_{Y_i}^{2}})$$

In [6]:
modelg=GaussianNB()
modelg.fit(X_train,y_train)
modelg.predict(X_test)

array([2, 2, 2, 2, 1, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0, 2, 1, 1, 1, 0, 1,
       0, 2, 2, 1, 0, 2, 1, 1, 0, 1, 2, 0, 2, 0, 0, 1, 1, 0, 0, 2, 1, 0,
       1])

In [7]:
modelg.predict_proba(X_test)

array([[5.99054036e-135, 1.70149305e-002, 9.82985069e-001],
       [3.59318950e-182, 7.56719444e-007, 9.99999243e-001],
       [1.09335661e-234, 2.96613386e-012, 1.00000000e+000],
       [7.71997428e-121, 6.63461469e-002, 9.33653853e-001],
       [1.17131930e-098, 6.97319586e-001, 3.02680414e-001],
       [1.94583828e-049, 9.99979112e-001, 2.08875450e-005],
       [1.00000000e+000, 4.79708975e-017, 2.59248946e-026],
       [1.87433131e-060, 9.99966524e-001, 3.34755217e-005],
       [1.00000000e+000, 1.82638859e-013, 3.20125409e-022],
       [1.00000000e+000, 8.17337488e-017, 6.13473838e-026],
       [7.82620635e-115, 1.23594696e-001, 8.76405304e-001],
       [1.00000000e+000, 1.93939739e-016, 1.15362596e-025],
       [4.34560782e-070, 9.99812522e-001, 1.87477843e-004],
       [1.00000000e+000, 2.65075740e-018, 1.18241378e-027],
       [1.00000000e+000, 1.85431881e-015, 6.08652788e-025],
       [1.00000000e+000, 2.88573009e-016, 5.31943864e-026],
       [1.34074686e-172, 2.98820466e-004

In [8]:
print('Training Set Score:',modelg.score(X_train,y_train))
print('Test Set Score:',modelg.score(X_test,y_test))

Training Set Score: 0.9523809523809523
Test Set Score: 0.9555555555555556


# Multinomial Naive Bayes
主要用在離散變數，比方說次數、類別等等。
$$ P(Y_i)=\frac{N_{Y_i}+\alpha}{N+K_\alpha} $$$$ $$$$P(X_j|Y_i)=\frac{N_{Y_i,x_j}+\alpha}{N_{Y_i}+n\alpha} $$

In [14]:
modelm=MultinomialNB() # MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
modelm.fit(X_train,y_train) #alpha預設為1
modelm.predict(X_test)

array([2, 2, 2, 2, 1, 1, 0, 1, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 0, 2, 1, 0,
       2])

In [10]:
modelm.predict_proba(X_test)

array([[0.01299652, 0.43310652, 0.55389697],
       [0.01102474, 0.44408174, 0.54489352],
       [0.00636482, 0.43219805, 0.56143712],
       [0.02193628, 0.45379454, 0.52426918],
       [0.05696759, 0.48622165, 0.45681076],
       [0.08998553, 0.46421484, 0.44579963],
       [0.73837117, 0.16510912, 0.09651971],
       [0.0676879 , 0.46785211, 0.46445999],
       [0.72690742, 0.17436479, 0.09872779],
       [0.74432283, 0.16254256, 0.09313462],
       [0.02558632, 0.45665205, 0.51776163],
       [0.70784646, 0.18241304, 0.1097405 ],
       [0.05286655, 0.46483281, 0.48230064],
       [0.8219141 , 0.11717488, 0.06091102],
       [0.79447892, 0.13442503, 0.07109606],
       [0.63280324, 0.22067602, 0.14652074],
       [0.00936422, 0.43603189, 0.55460389],
       [0.051616  , 0.47673706, 0.47164694],
       [0.06195888, 0.47470584, 0.46333528],
       [0.02751536, 0.45487577, 0.51760888],
       [0.73049274, 0.1697659 , 0.09974136],
       [0.03784748, 0.45967267, 0.50247985],
       [0.

In [11]:
print('Training Set Score:',modelm.score(X_train,y_train))
print('Test Set Score:',modelm.score(X_test,y_test))

Training Set Score: 0.8380952380952381
Test Set Score: 0.8


# Bernoulli Naive Bayes
用在二元的特徵，比方說特徵是否出現、特徵大小、特徵長短等等這種二元的分類。
$$ P(X_j|Y_i)=P_{Y_i}^{X_j}(1-P_{Y_i})^{X_j} $$

In [12]:
modelb = BernoulliNB()
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [15]:
modelb = BernoulliNB(binarize=1) #特徵切分 設1拆成0與1
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0,
       2])

In [16]:
modelb.score(X_test,y_test)

0.6444444444444445

In [17]:
X=pd.DataFrame(X)
X.describe() #4個特徵個別差異

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [18]:
modelb = BernoulliNB(binarize=[5.8,3,4.35,1.3]) #中位數拆分
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([2, 2, 2, 2, 2, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 2, 1, 2, 0, 2,
       0, 2, 2, 1, 0, 2, 2, 2, 0, 1, 2, 1, 2, 0, 1, 2, 1, 0, 1, 2, 2, 0,
       2])

In [19]:
modelb.predict_proba(X_test)

array([[6.43073980e-04, 4.16805382e-01, 5.82551544e-01],
       [7.91385636e-05, 5.20131944e-02, 9.47907667e-01],
       [7.91385636e-05, 5.20131944e-02, 9.47907667e-01],
       [4.24954940e-06, 8.37894809e-02, 9.16206270e-01],
       [7.91385636e-05, 5.20131944e-02, 9.47907667e-01],
       [4.47625622e-01, 5.52143756e-01, 2.30622306e-04],
       [9.60480910e-01, 3.94915982e-02, 2.74917639e-05],
       [4.47625622e-01, 5.52143756e-01, 2.30622306e-04],
       [9.60480910e-01, 3.94915982e-02, 2.74917639e-05],
       [9.60480910e-01, 3.94915982e-02, 2.74917639e-05],
       [7.91385636e-05, 5.20131944e-02, 9.47907667e-01],
       [9.60480910e-01, 3.94915982e-02, 2.74917639e-05],
       [4.47625622e-01, 5.52143756e-01, 2.30622306e-04],
       [9.60480910e-01, 3.94915982e-02, 2.74917639e-05],
       [9.60480910e-01, 3.94915982e-02, 2.74917639e-05],
       [4.47625622e-01, 5.52143756e-01, 2.30622306e-04],
       [4.24954940e-06, 8.37894809e-02, 9.16206270e-01],
       [7.91385636e-05, 5.20131

In [20]:
print('Training Set Score:',modelb.score(X_train,y_train))
print('Test Set Score:',modelb.score(X_test,y_test))

Training Set Score: 0.8571428571428571
Test Set Score: 0.7111111111111111
